apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-worker
  template:
    metadata:
      labels:
        app: orders-worker
    spec:
      containers:
        - name: orders-worker
          image: 583164063998.dkr.ecr.us-east-1.amazonaws.com/orders-worker:latest
          envFrom:
            - configMapRef:
                name: orders-config
            - secretRef:
                name: orders-secret
          resources:
            requests:
              memory: 32Mi
              cpu: 25m
            limits:
              memory: 128Mi
              cpu: 250m
